### ISSUE TITLE
Cypress not pulling Tailwind 4.0 styles in Angular 19

### ISSUE THREAD

**Issue by denious** [cypress-io/cypress-component-testing-apps#49]
Hi all,

Is there a plan to upgrade the Angular setup in this repo to Tailwind 4.0?

The Tailwind recommended installation and style import methods have slightly changed, and I'm assuming something about that may no longer be pulling Tailwind styles into the Component Testing setup.

If there is a better place to ask this question, please let me know.

### Stack
- Angular 19.2 w/ SCSS
- Tailwind 4.0 via PostCSS
- Cypress 14.2

### styles.scss
```css
@use "tailwindcss";
@use "primeicons/primeicons.css";

html {
  font-size: 14px;
  font-family: 'Inter', sans-serif;
  font-optical-sizing: auto;
  font-style: normal;
  background-color: var(--p-surface-50);
}

h1 {
  font-size: 2.286rem;
}

h2 {
  font-size: 1.714rem;
  font-weight: 700;
  margin: 1.5rem 0;
}

h3 {
  font-size: 1.429rem;
}
```

### Tailwind styles not applied
![Image](https://github.com/user-attachments/assets/2a7f2b73-4979-447b-bbdf-2a9d48afecb9)

Thanks,
Denis
